# Python basics 

by Vikarm Khaire (21 August 2021) 
Applicable for version 3.0 and above

* Printing output: use print(); Print() does not work (python is case sensitive)

In [1]:
print("Hellow class")

Hellow class


In [2]:
print(2+3-3*10)

-25


Note: in jupyter notebook or ipython you don't have to write print()

In [3]:
2+3-3*10

-25

In [4]:
print(27/11); print(27/9); print(27/10); print(3*4)

2.4545454545454546
3.0
2.7
12


In [5]:
a=25.0
b=334
c='vikram'
d=False
e=[2, 3, 4.9, 'yes', 'india']
print(a); print(b); print(c); print(d); print(e)

25.0
334
vikram
False
[2, 3, 4.9, 'yes', 'india']


* Types of the inputs (Float, Integer, String, Boolean) 

In [6]:
print(type(a))

<class 'float'>


In [7]:
print(type(b))

<class 'int'>


In [8]:
print(type(c))

<class 'str'>


In [9]:
print(type(d))

<class 'bool'>


In [10]:
print(type(e))

<class 'list'>


* Operations on different types

In [11]:
print('a'+'b')

ab


In [12]:
print(a+b)

359.0


True and False are very important booleans 

In [13]:
print(True + False)

1


In [14]:
print(True); print(True*2)

True
2


In [15]:
print(True * False)

0


... because True=1 & False=0 (use True not true)

* Changing the type for some operation

In [16]:
x='Answer to life the universe and everything is '
ans=42
print(x + str(ans) + '! :)')

Answer to life the universe and everything is 42! :)


In [17]:
a=5
b=5
c=a*b
print(str(a)+' times '+str(b) +' equals '+str(c))

5 times 5 equals 25


* List manipulations (note actual arrays will be slightly different)

In [18]:
e=[2,3,5,3.5, 9, 8, 'yes', 'india', 'last']
print(e)

[2, 3, 5, 3.5, 9, 8, 'yes', 'india', 'last']


In [19]:
a=e
print(a)

[2, 3, 5, 3.5, 9, 8, 'yes', 'india', 'last']


...here 'a' is new list but it is not correct way to define 'a', as you can see later

In [20]:
print(a[0])
print(a[-1])
print(a[4])

2
last
9


... array/list starts from index 0 and index -1 is the last number in list/array (cool!)

In [21]:
print(a[0:5])
print(a[:5])
print(a[5:9])
print(a[5:])

[2, 3, 5, 3.5, 9]
[2, 3, 5, 3.5, 9]
[8, 'yes', 'india', 'last']
[8, 'yes', 'india', 'last']


...a[x:y] will slice array from xth element to (y-1)th element 
...also a[x:] will pick all numbers after xth element including xth element
...similarly a[:y] will pick all elements before yth element (not including yth element)

In [22]:
a[::2]

[2, 5, 9, 'yes', 'last']

quick way of reversing array

In [23]:
a[::-1]

['last', 'india', 'yes', 8, 9, 3.5, 5, 3, 2]

In [24]:
# example 1d list manipulation
aa=[0,1,2,3,4,5,6,7,8,9,10,11,12]
print(aa[: :2]) # select elements with seperation 2
print(aa[1: :2])# select elements with seperation 2 but from second element
print(aa[: :5]) # select elements with seperation 5
print(aa[: :1]) # select elements with seperation 1= same array
print(aa[: :-1])# select elements with seperation -1= array reversed
print(aa[: :-2])# select elements with seperation -2 
print(aa[:1 :-2])# select elements with seperation -2 but up to second  last element

[0, 2, 4, 6, 8, 10, 12]
[1, 3, 5, 7, 9, 11]
[0, 5, 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[12, 10, 8, 6, 4, 2, 0]
[12, 10, 8, 6, 4, 2]


In [25]:
print(a)

[2, 3, 5, 3.5, 9, 8, 'yes', 'india', 'last']


In [26]:
print(e)

[2, 3, 5, 3.5, 9, 8, 'yes', 'india', 'last']


...notice that both lists are same  ... now delete an element of a with del() function

In [27]:
del(a[0])

In [28]:
print(a)

[3, 5, 3.5, 9, 8, 'yes', 'india', 'last']


In [29]:
print(e)

[3, 5, 3.5, 9, 8, 'yes', 'india', 'last']


...notice that you deleted first element in list a but it got deleted from list e as well   ...reason for this is the way we assigned the list a and e in Input line [16], it did not create another array rather just give two different name to the stored array/list 

...correct way of doing this (creating new array a which is same as b so that you play with a without screawing e) 
is as follows

In [30]:
a=list(e)

In [31]:
del(a[4:])
print(a)
print(e)

[3, 5, 3.5, 9]
[3, 5, 3.5, 9, 8, 'yes', 'india', 'last']


...another way is

In [32]:
b=e[:]
del(b[:5])
print(b)
print(e)

['yes', 'india', 'last']
[3, 5, 3.5, 9, 8, 'yes', 'india', 'last']


* Functions

In [33]:
print(a)
print(max(a))

[3, 5, 3.5, 9]
9


... we have already used function such as print, type, str, del 

... to know how a particular function works use help(function_name) or ?function_name

In [34]:
help(max) 

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



... here note that these functions are far more capable than they look (google or visit wiki.python.org for their full functions)... the argument between "[, ]" or having = sign need not to be provided... if not provided they use default values ...for example use a sorted function

In [35]:
a=[3, 4, 5.9, 2.99, 9]
print(sorted(a))

[2.99, 3, 4, 5.9, 9]


In [36]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [37]:
print(sorted(a, reverse=True))

[9, 5.9, 4, 3, 2.99]


... key=None has taken by default here. also note that reverse can have 0 or 1 value instead of True or False

... let us look at some more functions

In [38]:
print(len(a))

5


In [39]:
print(min(a))

2.99


... note that some function only work on few object types for example 

In [40]:
x=2.99
print(len(x))

TypeError: object of type 'float' has no len()

In [41]:
print(int(x))

2


In [42]:
print(int(a))

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [43]:
print(len(x))

TypeError: object of type 'float' has no len()

* Methods: Calling a function on object using object.function

In [44]:
a=[3, 4, 5.9, 2.99, 9]
print(a.index(9))

4


In [45]:
name='vikram'
print(name)
print(name.capitalize())

vikram
Vikram


In [46]:
city='thiruvananthapuram'
print(city.count("a"))

4


In [47]:
line="Answer to life the universe and everything is"
v=line.split()
print(v)

['Answer', 'to', 'life', 'the', 'universe', 'and', 'everything', 'is']


In [48]:
v.append("42!")
print(v)

['Answer', 'to', 'life', 'the', 'universe', 'and', 'everything', 'is', '42!']


In [49]:
y="".join(v)
print(y)

Answertolifetheuniverseandeverythingis42!


In [50]:
y=" ".join(v)
print(y)

Answer to life the universe and everything is 42!


...note that some methods change the objects (objects are all the variable you define/create) themselves, be careful about them (example append function). THE METHODS ARE RICH!  Just type help(str) and see how many methods are there for string objects. (on ipython terminal use q to quit the help)

# Packages

... Packages make python powerful. Packages are separate pack of programs and functions designed for specific purpose. For data science its NumPy (numeric package) or scientific computation its SciPy or for astronomy its AstroPy. NumPy is one of the most important packages in python. 

... Packages are not in-built in the python. If installed with Anaconda (link ) you can get all necessary packages. Packages are needed to call in th python program using command import as illustrated below. 

In [51]:
import numpy as np
a=[1.2, 2.4, 0.5, 9, 7, 6, 8, 4.9]
b=np.array(a)
print(b)

[1.2 2.4 0.5 9.  7.  6.  8.  4.9]


... Note that 'np' is a given name by me to numpy package. Array is specific type of function in numpy, quite handy in playing with data. So since I called np to numpy, I can write np.array rather than numpy.array. 

...There are two ways to import: either you can import entire package as done above so that everything in that package is available to you OR import a particular function/object from packages as: 

In [52]:
from numpy import array as my_array
c=my_array(a)
print(c)

[1.2 2.4 0.5 9.  7.  6.  8.  4.9]


... I prefer the first way to reduce the confusion

...Few examples do matrix inversion as follow

In [53]:
import scipy as sc
A=np.array([[1, 2],[3, 4]])
print(A)

[[1 2]
 [3 4]]


In [54]:
from scipy import linalg
B=linalg.inv(B)
print(B)

NameError: name 'B' is not defined

In [55]:
# check if inversion is correct
print(np.dot(A,B))

NameError: name 'B' is not defined

... Now let us look at some advantages of using numpy arrays

In [56]:
a=[1.2, 2.4, 0.5, 9, 7, 6, 8, 4.9]
npa=np.array(a)
print(npa+20)

[21.2 22.4 20.5 29.  27.  26.  28.  24.9]


In [57]:
print(npa>2)

[False  True False  True  True  True  True  True]


In [58]:
y=npa>2
print(npa[y])

[2.4 9.  7.  6.  8.  4.9]


...splicing is same as in lists

In [59]:
print(npa)
print(npa[0:5])

[1.2 2.4 0.5 9.  7.  6.  8.  4.9]
[1.2 2.4 0.5 9.  7. ]


...but operations are different; for example

In [60]:
print(a+a)

[1.2, 2.4, 0.5, 9, 7, 6, 8, 4.9, 1.2, 2.4, 0.5, 9, 7, 6, 8, 4.9]


In [61]:
print(npa+npa)

[ 2.4  4.8  1.  18.  14.  12.  16.   9.8]


...also list can have mix of types which is not allowed in np.array; for example

In [62]:
t1=np.array(['ab', 'cdd', 95, True])
print(t1)

['ab' 'cdd' '95' 'True']


...everything converted into strings or

In [63]:
t2=np.array([False, 3.0, 95, True])
print(t2)

[ 0.  3. 95.  1.]


...everything converted into floats. And addition of these will give you error message

In [64]:
print(t1+t2)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

how to create array

In [65]:
# created arrat from having numbers 0 to 9
num_array = np.arange(10)
print(num_array)

[0 1 2 3 4 5 6 7 8 9]


In [66]:
print(np.linspace(0, 9, 10)) #another way

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


some very important simple functions ...

In [67]:
np.mean(num_array)

4.5

In [68]:
np.median(num_array)

4.5

In [69]:
np.max(num_array)

9

In [70]:
np.min(num_array)

0

In [71]:
np.std(num_array)

2.8722813232690143

n-dimensional array or matrices

In [72]:
import scipy as sc
A=np.array([[1, 2],[3, 4]])
print(A)

[[1 2]
 [3 4]]


In [73]:
print(A.shape)

(2, 2)


In [74]:
num_array.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

do the matrix inversion ---easy way

In [75]:
from scipy import linalg
B=linalg.inv(A)
print(B)

[[-2.   1. ]
 [ 1.5 -0.5]]


.... Important note: we are not going to use many fancy functions in the course unless told otherwise

Follow the instructions of teacher 

# if and for loop

The most important loops in any programming languague ('while' is just a for loop with if)

In [76]:
a = 30
b = 40 
if a < b:
    print('a is less than', b)

a is less than 40


In [77]:
if a is not b:
    print('a is not', b)

a is not 40


In [78]:
if a != b:
    print('a is not', b)

a is not 40


... for loop