# System of linear equations

-Vikram Khaire; Date: September 06, 2021 

### Gauss elimination method

Let's start with an example 
    

$x_0 + 2x_1 + 3x_2 = 5$

$2 x_0 + x_1 + x_2 = 4$

$ 3x_0 + 5 x_1 + 7 x_2 = 13$


Ax = y where x = [x0, x1, x2]

--for inversion
A ? $= I$ 

what is ?  ==> $A^{-1}$

In [1]:
import numpy as np

#### Create a augumented matrix.

Number of unknowns are  = 3

Dimension of augumented matrix  = (3,4) 

In [2]:
# an augmented matrix with dimension ()
A=np.array(([1., 2., 3., 5.],
          [2., 1., 1., 4.],
          [3., 5., 7., 13.]))


In [3]:
A

array([[ 1.,  2.,  3.,  5.],
       [ 2.,  1.,  1.,  4.],
       [ 3.,  5.,  7., 13.]])

In [4]:
A.shape

(3, 4)

In [5]:
A[2][3]

13.0

#### First elimination :

make A[1][0] = 0 and A[2][0] = 0

second row --> multiply first row by 2 and subtract from second

third row --> multiply first row by 3 and subtract from third

row A[1] ==> row A[1] - A[1][0]/A[0][0] * row A[0]

row A[2] ==> row A[2] - A[2][0]/A[0][0] * row A[0]

In [6]:
A[1] =  A[1] - A[1][0]/A[0][0] *A[0]

"""
for i in range(1, 4): # i is from 1 to 4  <== true?
    A[1][i] =  A[1][i] - A[1][0]/A[0][0] *A[0][i]
"""

A[2] =  A[2] - A[2][0]/A[0][0] *A[0]

In [7]:
A

array([[ 1.,  2.,  3.,  5.],
       [ 0., -3., -5., -6.],
       [ 0., -1., -2., -2.]])

#### Second elimination

row A[2] ==> row A[2] - A[2][1]/A[1][1] * row A[1]

In [8]:
A[2] =  A[2] - A[2][1]/A[1][1] *A[1]

In [9]:
A

array([[ 1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.        , -3.        , -5.        , -6.        ],
       [ 0.        ,  0.        , -0.33333333,  0.        ]])

### Back substitution 

x2 = A[2][3]/A[2][2] 

x1 = (A[1][3] - x2 * A[1][2]) / A[1][1]

x0 = (A[0][3]- x1 * A[0][1] - x2 * A[0][2]) / A[0][0]

In [10]:
x2 = A[2][3]/A[2][2] 

x1 = (A[1][3] - x2 * A[1][2])/A[1][1]

x0 = (A[0][3] - x2 * A[0][2]- x1 * A[0][1])/A[0][0]

In [11]:
print( x0, x1, x2) # our solution

1.0 2.0 -0.0


### Write a general code

In [12]:
B=np.array(([1., 2., 3., 5.],
          [2., 1., 1., 4.],
          [3., 5., 7., 13.]))

In [13]:
# let's write pieces of code

n = B.shape[0] # number of unknowns

# gausss elimination
for i in range(n):
    for j in range(i+1, n):
        ratio = B[j][i]/B[i][i]
        print(ratio)
        for k in range (n+1): # element by element assignment
            B[j][k] = B[j][k] - ratio * B[i][k]
    

2.0
3.0
0.3333333333333333


In [14]:
C=np.array(([1., 2., 3., 5.],
          [2., 1., 1., 4.],
          [3., 5., 7., 13.]))

B=np.array(([1., 2., 3., 5.],
          [2., 1., 1., 4.],
          [3., 5., 7., 13.]))

In [15]:

n = C.shape[0] # number of unknowns

# gausss elimination
for i in range(n):
    for j in range(i+1, n):
        ratio = C[j][i]/C[i][i]
        print(ratio)
        C[j] = C[j]- ratio*C[i] # Churchil's suggestion


2.0
3.0
0.3333333333333333


In [16]:
C

array([[ 1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.        , -3.        , -5.        , -6.        ],
       [ 0.        ,  0.        , -0.33333333,  0.        ]])

In [23]:
# back substitution
solution = np.zeros(n)

solution[n-1] = C[n-1][n]/ C[n-1][n-1]
# x2 for perticular problem

for i in range(n-2, -1, -1):
    #i = 1 x= x1
    solution[i]= A[i][n]
    for j in range(i+1, n):
        solution[i]=  solution[i]- solution[j]*C[i][j]
        
    # out of the for loop on j
    solution[i]= solution[i]/C[i][i]
    
# just copying ....
#x1 = (A[1][3] - x2 * A[1][2])/A[1][1]
#x0 = (A[0][3] - x2 * A[0][2]- x1 * A[0][1])/A[0][0]

In [24]:
solution

array([ 1.,  2., -0.])

In [26]:
# another way
# back substitution
solution = np.zeros(n)
for i in range(n-1, -1, -1):
    solution[i]= A[i][n]
    for j in range(i+1, n):
        solution[i]=  solution[i]- solution[j]*C[i][j]
        
    # out of the for loop on j
    solution[i]= solution[i]/C[i][i]

print(solution)

[ 1.  2. -0.]


In [27]:
# now write general function for Gauss-elimination method

def gauss_eliminate(C):
    """
    param C: Augumented matrix
    returns : Augumented Upper triangular matrix & solution vector
    """
    
    n = C.shape[0] # number of unknowns
    # gausss elimination
    for i in range(n):
        for j in range(i+1, n):
            ratio = C[j][i]/C[i][i]
            C[j] = C[j]- ratio*C[i] 
            
    # back substitution
    solution = np.zeros(n)
    for i in range(n-1, -1, -1):
        solution[i]= A[i][n]
        for j in range(i+1, n):
            solution[i]=  solution[i]- solution[j]*C[i][j]
        
        # out of the for loop on j
        solution[i]= solution[i]/C[i][i]
        
        
    return C, solution
    

In [28]:
B=np.array(([1., 2., 3., 5.],
          [2., 1., 1., 4.],
          [3., 5., 7., 13.]))
a, sol = gauss_eliminate(B)

In [31]:
print(a)
print(sol)

[[ 1.          2.          3.          5.        ]
 [ 0.         -3.         -5.         -6.        ]
 [ 0.          0.         -0.33333333  0.        ]]
[ 1.  2. -0.]


#### Gauss-Jorden elimination method

to make coefficient matrix = I (identity matrix)

In [39]:
C=np.array(([1., 2., 3., 5.],
          [2., 1., 1., 4.],
          [3., 5., 7., 13.]))

n = C.shape[0] # number of unknowns

# gausss-jorden elimination
for i in range(n):
    for j in range(n):
        if j!=i:
            ratio = C[j][i]/C[i][i]
            C[j] = C[j]- ratio*C[i]
            
# solution 
for i in range(n):
    print('x{}='.format(i), C[i][n]/C[i][i])
    
# identity matrix

for i in range(n):
    C[i] = C[i]/C[i][i] 

print(C)

x0= 1.0
x1= 2.0
x2= -0.0
[[ 1.  0.  0.  1.]
 [-0.  1. -0.  2.]
 [-0. -0.  1. -0.]]


In [57]:
# writing general code for Gauss-Jorden elimination 

def gauss_jorden_eliminate(C):
    """
    param C: Augumented matrix
    returns : Augumneted identity matrix & solution vector
    """
    
    n = C.shape[0] # number of unknowns

    # gausss-jorden elimination
    for i in range(n):
        for j in range(n):
            if j!=i:
                ratio = C[j][i]/C[i][i]
                C[j] = C[j]- ratio*C[i]

    # identity matrix
    for i in range(n):
        C[i] = C[i]/C[i][i] 
        
    return C, C[:, n]

#see why C[:,n] is differnet than C[:][n]

In [58]:
B=np.array(([1., 2., 3., 5.],
          [2., 1., 1., 4.],
          [3., 5., 7., 13.]))
a, sol = gauss_jorden_eliminate(B)
print(a)
print(sol)

[[ 1.  0.  0.  1.]
 [-0.  1. -0.  2.]
 [-0. -0.  1. -0.]]
[ 1.  2. -0.]


### Matrix inversion 

$A A^{-1} = I$

In [75]:
# find inverse of this matrix
B=np.array(([1., 2., 3.],
          [2., 1., 1.],
          [3., 5., 7.]))

In [76]:
# write pieces of codes
# crete auguemented matrix
n = B.shape[0]

#intialize auguemented matrix
C= np.zeros((n, 2*n))

for i in range(n): #rows
    for j in range (2*n):
        if j <n:
            C[i][j]= B[i][j]
        elif j == (i+n): 
            C[i][j] = 1

In [77]:
# gauss-jorden elimination (copying from above cells)
for i in range(n):
    for j in range(n):
        if j!=i:
            ratio = C[j][i]/C[i][i]
            C[j] = C[j]- ratio*C[i]
            
# identity matrix
for i in range(n):
    C[i] = C[i]/C[i][i] 


In [78]:
C

array([[  1.,   0.,   0.,   2.,   1.,  -1.],
       [ -0.,   1.,  -0., -11.,  -2.,   5.],
       [ -0.,  -0.,   1.,   7.,   1.,  -3.]])

In [79]:
# print inverse matrix
C[:, n:]

array([[  2.,   1.,  -1.],
       [-11.,  -2.,   5.],
       [  7.,   1.,  -3.]])

In [80]:
# custom function
from numpy.linalg import inv
inv(B)

array([[  2.,   1.,  -1.],
       [-11.,  -2.,   5.],
       [  7.,   1.,  -3.]])

In [82]:
# write a general function

def matrix_inversion(B):
    """
    param B: nxn matrix (with det(B)!=0)
    returns : inverse of B
    """
    
    # crete auguemented matrix
    n = B.shape[0]

    #intialize auguemented matrix
    C= np.zeros((n, 2*n))

    for i in range(n): #rows
        if C[i][i]==0:
            print('ohohoho..... diagonal emelment is zero!')
            break
        
        for j in range (2*n):
            if j <n:
                C[i][j]= B[i][j]
            elif j == (i+n): 
                C[i][j] = 1
    
    # gauss-jorden elimination 
    for i in range(n):
        for j in range(n):
            if j!=i:
                ratio = C[j][i]/C[i][i]
                C[j] = C[j]- ratio*C[i]

    # identity matrix
    for i in range(n):
        C[i] = C[i]/C[i][i] 
        
    return C[:, n:]
